package embed

import _ "embed"

// WorkerJS contains the Worker ESM module (source, git-tracked).
//
//go:embed worker/worker.mjs
var WorkerJS []byte

// DaemonBinary is the cross-compiled edgessh-noded binary for linux/amd64.
// Build artifact — generated by `make daemon`, gitignored.
//
//go:embed edgessh-noded
var DaemonBinary []byte

// Image is the full OCI image (ubuntu + tools + edgessh-noded), gzip-compressed tarball.
// Build artifact — generated by `make image`, gitignored.
//
//go:embed edgessh-image.tar.gz
var Image []byte
